#!/usr/bin/env bash
# Generates `CAPM Prep (Mobile).command` on the Desktop.
#
# Double-clicking it:
#   1. Starts the production server if it isn't running
#   2. Opens an SSH tunnel to free.pinggy.io (no install, no signup, port 443)
#   3. Prints a public https://<random>.run.pinggy-free.link URL
#   4. Opens that URL on the Mac (Safari) so you can:
#      a) confirm it works
#      b) generate a QR code by Cmd+L → right-click → Show QR Code (in some browsers)
#      OR just text/AirDrop the URL to your phone.
#
# Tunnel is FREE TIER: expires in ~60 minutes; each launch yields a new URL.
# For a stable permanent URL, sign up at pinggy.io and use a paid token,
# or run `tailscale funnel` if you have a Tailscale account.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
COMMAND_PATH="$HOME/Desktop/CAPM Prep (Mobile).command"

cat > "$COMMAND_PATH" <<EOF
#!/usr/bin/env bash
# CAPM Prep mobile launcher — generated by install-mobile-command.sh
set -e
cd "$PROJECT_ROOT"

# 1. Make sure the local server is up
if ! /usr/bin/curl -s -o /dev/null -w '%{http_code}' http://localhost:3000 | grep -qE '^(2|3)'; then
  echo "Local server not running — starting it…"
  NPM=\$(/bin/zsh -lc 'command -v npm' 2>/dev/null || true)
  if [ -z "\$NPM" ]; then
    echo "ERROR: npm not found. Install Node.js first." >&2
    read -n1 -srp 'Press any key to close…'
    exit 1
  fi
  NODE_DIR=\$(/usr/bin/dirname "\$NPM")
  export PATH="\$NODE_DIR:\$PATH"
  nohup "\$NPM" start > /tmp/capm-prep.log 2>&1 &
  disown
  for i in \$(seq 1 60); do
    /usr/bin/curl -s -o /dev/null -w '%{http_code}' http://localhost:3000 \\
      | grep -qE '^(2|3)' && break
    sleep 0.5
  done
fi

# 2. Kill any old tunnel
/usr/bin/pkill -f "ssh.*pinggy" 2>/dev/null || true
sleep 1

# 3. Open SSH tunnel to pinggy.io (port 443, traverses any firewall/DNS issue)
echo
echo "Opening public tunnel via Pinggy (free, ~60 min duration)…"
/usr/bin/nohup /usr/bin/ssh -p 443 -o StrictHostKeyChecking=no \\
  -o ServerAliveInterval=30 \\
  -R0:localhost:3000 \\
  free.pinggy.io \\
  > /tmp/pinggy.log 2>&1 &
disown

# 4. Wait for the URL to appear
URL=""
for i in \$(seq 1 30); do
  URL=\$(/usr/bin/grep -oE 'https://[a-z0-9-]+\\.[a-z-]+\\.pinggy[a-z-]*\\.link' /tmp/pinggy.log 2>/dev/null | head -1)
  [ -n "\$URL" ] && break
  sleep 0.5
done

if [ -z "\$URL" ]; then
  echo
  echo "Couldn't get a public URL. Tunnel log:"
  cat /tmp/pinggy.log
  read -n1 -srp 'Press any key to close…'
  exit 1
fi

# 5. Wait for the URL to actually be reachable
for i in \$(seq 1 20); do
  R=\$(/usr/bin/curl -m 5 -sL -o /dev/null -w '%{http_code}' "\$URL")
  [ "\$R" = "200" ] && break
  sleep 1
done

# 6. Show + open on the Mac
LAN_IP=\$(/usr/sbin/ipconfig getifaddr en0 2>/dev/null || /usr/sbin/ipconfig getifaddr en1 2>/dev/null || echo unknown)
echo
echo "════════════════════════════════════════════════════════════════════"
echo
echo "  📱  On your phone (anywhere, any network):"
echo "       \$URL"
echo
echo "  🏠  On your Wi-Fi only:    http://\$LAN_IP:3000"
echo "  💻  On this Mac:           http://localhost:3000"
echo
echo "  ⚠️   Public URL expires in ~60 min. Re-launch this app for a new one."
echo "  ⚠️   Tunnel dies if Mac sleeps. Keep the lid open."
echo
echo "════════════════════════════════════════════════════════════════════"

# Copy URL to clipboard for easy paste into Messages/AirDrop to phone
echo -n "\$URL" | /usr/bin/pbcopy 2>/dev/null && echo "(URL copied to clipboard)"

# Open in Mac browser too
/usr/bin/open "\$URL"

echo
echo "Tip: Open Messages on Mac, paste (⌘V) the URL, send to yourself,"
echo "     then tap it on your phone. Faster than typing the random subdomain."
echo
read -n1 -srp 'Press any key to close this window (tunnel keeps running)…'
EOF

chmod +x "$COMMAND_PATH"
echo "Installed: $COMMAND_PATH"
