#!/usr/bin/env bash
# Alternate desktop launcher: a plain `.command` file instead of a `.app`.
#
# Trade-off: .command opens a small Terminal window (uglier) but it's NOT
# subject to the Gatekeeper "developer cannot be verified" prompt that
# unsigned .app bundles trigger on first double-click. Useful if you don't
# want to do the right-click → Open dance.
#
# After it runs, you can close the Terminal window — the server keeps
# running in the background.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
COMMAND_PATH="$HOME/Desktop/CAPM Prep.command"

cat > "$COMMAND_PATH" <<EOF
#!/usr/bin/env bash
# CAPM Prep launcher — generated by scripts/desktop-app/install-command.sh
set -e
cd "$PROJECT_ROOT"

# Print the URL to use from another device on the same Wi-Fi.
print_lan_url() {
  local IP
  IP=\$(/usr/sbin/ipconfig getifaddr en0 2>/dev/null || /usr/sbin/ipconfig getifaddr en1 2>/dev/null || true)
  if [ -n "\$IP" ]; then
    echo ""
    echo "  📱  On your phone (same Wi-Fi):  http://\$IP:3000"
    echo "  💻  On this Mac:                  http://localhost:3000"
    echo ""
  fi
}

# If port 3000 is already serving, just open the browser.
if /usr/bin/curl -s -o /dev/null -w '%{http_code}' http://localhost:3000 | grep -qE '^(2|3)'; then
  print_lan_url
  /usr/bin/open http://localhost:3000
  exit 0
fi

# Resolve npm reliably (zsh login shell loads ~/.zprofile so brew/volta paths work).
NPM=\$(/bin/zsh -lc 'command -v npm' 2>/dev/null || true)
if [ -z "\$NPM" ]; then
  echo "ERROR: npm not found on PATH. Install Node.js first." >&2
  read -n1 -srp 'Press any key to close…'
  exit 1
fi

# When Finder double-clicks this .command, PATH is the bare launchd PATH
# (typically /usr/bin:/bin:/usr/sbin:/sbin) — no /usr/local/bin. npm's
# shebang then fails to find node. Prepend node's directory explicitly.
NODE_DIR=\$(/usr/bin/dirname "\$NPM")
export PATH="\$NODE_DIR:\$PATH"

# Self-heal: if the production build is missing or stale, rebuild before
# starting. \`npm start\` will hard-fail with "Could not find a production
# build" otherwise — that's how this launcher silently broke before.
NEXT_BUILD_ID="\$(/bin/cat "\$(/usr/bin/dirname "\$0")/../CAPM/.next/BUILD_ID" 2>/dev/null || true)"
NEXT_BUILD_ID_LOCAL="\$(/bin/cat "$PROJECT_ROOT/.next/BUILD_ID" 2>/dev/null || true)"
if [ -z "\$NEXT_BUILD_ID_LOCAL" ]; then
  echo "Production build missing — running 'npm run build' first (one-time, ~30s)…"
  if ! "\$NPM" run build > /tmp/capm-prep-build.log 2>&1; then
    echo "Build failed. See /tmp/capm-prep-build.log" >&2
    /usr/bin/tail -20 /tmp/capm-prep-build.log >&2
    read -n1 -srp 'Press any key to close…'
    exit 1
  fi
  echo "Build OK."
fi

echo "Starting CAPM Prep server in background…"
nohup "\$NPM" start > /tmp/capm-prep.log 2>&1 &
disown

# Poll for ~30s.
for i in \$(seq 1 60); do
  if /usr/bin/curl -s -o /dev/null -w '%{http_code}' http://localhost:3000 | grep -qE '^(2|3)'; then
    print_lan_url
    /usr/bin/open http://localhost:3000
    echo "Open. You can close this window — the server keeps running."
    exit 0
  fi
  sleep 0.5
done

echo "Server didn't start in 30s. Check /tmp/capm-prep.log." >&2
read -n1 -srp 'Press any key to close…'
exit 1
EOF

chmod +x "$COMMAND_PATH"
echo "Installed: $COMMAND_PATH"
echo "Double-click it from your Desktop. A small Terminal window will open;"
echo "you can close it once the browser opens — the server keeps running."
